# Generated by Django 2.0 on 2019-10-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='显示'),
        ),
    ]
