# Generated by Django 2.0 on 2019-10-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20191017_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='显示'),
        ),
    ]
