# Generated by Django 2.0 on 2019-10-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='food.Tag', verbose_name='标签'),
        ),
    ]
