# Generated by Django 2.0 on 2019-10-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='mybody',
        ),
    ]
