# Generated by Django 2.0 on 2019-10-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20191024_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='mybody',
            new_name='excerpt',
        ),
    ]
